### ISSUE TITLE
Process `classifier (1)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by AparnaChauhan** [nf-core/ampliseq#150]
Hi, 
I'm facing an issue while running the following command -
nextflow run nf-core/ampliseq -profile cluster -c nextflow_1.config --reads Data_PRJEB25676 --extension '/*_{1,2}.fastq.gz' --FW_primer GTGCCAGCMGCCGCGGTAA --RV_primer GGACTACHVGGGTWTCTAAT --metadata Data_PRJEB25676/Metadata_PRJEB25676.tsv --outdir Output_PRJEB25676 --retain_untrimmed --trunclenf 240 --trunclenr 170 -resume

I'm new to using qiime2 and nf-core for microbiome analysis and I not able to figure out the cause for the error. I've posted the error log below.

```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'classifier (1)'

Caused by:
  Process `classifier (1)` terminated with an error exit status (1)

Command executed:

  qiime feature-classifier classify-sklearn  		--i-classifier GTGCCAGCMGCCGCGGTAA-GGACTACHVGGGTWTCTAAT-99-classifier.qza  		--p-n-jobs 8  		--i-reads rep-seqs.qza  		--o-classification taxonomy.qza  		--verbose
  
  qiime metadata tabulate  		--m-input-file taxonomy.qza  		--o-visualization taxonomy.qzv  		--verbose
  
  #produce "taxonomy/taxonomy.tsv"
  qiime tools export --input-path taxonomy.qza  		--output-path taxonomy
  
  qiime tools export --input-path taxonomy.qzv  		--output-path taxonomy

Command exit status:
  1

Command output:
  (empty)

Command error:
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/pickle.py", line 821, in save_dict
      self._batch_setitems(obj.items())
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/pickle.py", line 847, in _batch_setitems
      save(v)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/pickle.py", line 482, in save
      rv = reduce(obj)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/joblib/_memmapping_reducer.py", line 315, in __call__
      raise e
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/joblib/_memmapping_reducer.py", line 311, in __call__
      os.makedirs(self._temp_folder)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/os.py", line 210, in makedirs
      makedirs(head, mode, exist_ok)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/os.py", line 210, in makedirs
      makedirs(head, mode, exist_ok)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/os.py", line 220, in makedirs
      mkdir(name, mode)
  OSError: [Errno 30] Read-only file system: '/nfs/home/users'
  """
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
      results = action(**arguments)
    File "</opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/decorator.py:decorator-gen-347>", line 2, in classify_sklearn
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
      output_types, provenance)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
      output_views = self._callable(**view_args)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2_feature_classifier/classifier.py", line 218, in classify_sklearn
      confidence=confidence)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/q2_feature_classifier/_skl.py", line 45, in predict
      for chunk in _chunks(reads, chunk_size)) for m in c)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/joblib/parallel.py", line 1016, in __call__
      self.retrieve()
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/joblib/parallel.py", line 908, in retrieve
      self._output.extend(job.get(timeout=self.timeout))
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
      return future.result(timeout=timeout)
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/concurrent/futures/_base.py", line 432, in result
      return self.__get_result()
    File "/opt/conda/envs/nf-core-ampliseq-1.1.2/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
      raise self._exception
  _pickle.PicklingError: Could not pickle the task to send it to the workers.
  
  Plugin error from feature-classifier:
  
    Could not pickle the task to send it to the workers.
  
  See above for debug info.

Work dir:
  /nfs/home/students/achauhan/work/c8/6d8dcd29b34681cc4bca7998591590

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by d4straub** [comment]
It seems like you do not have writing right where it is required:

> OSError: [Errno 30] Read-only file system: '/nfs/home/users'

Probably you need to troubleshoot this with your admin/cluster support, this doesn't seem to be a problem with the pipeline.

**Comment by AparnaChauhan** [comment]
> Probably you need to troubleshoot this with your admin/cluster support, this doesn't seem to be a problem with the pipeline
But the same command for other datafile seems to work fine the classifier, in that I'm getting a completely different error.
```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'ancom_tax (study_title-level6)'

n error from composition:

    All values the `grouping` are the same. This method cannot operate on a grouping vector with only a single group of
samples(e.g., there are no 'between' variance because there is only a single group).Caused by:
  Process `ancom_tax (study_title-level6)` terminated with an error exit status (1)

Command executed:

  qiime taxa collapse 		--i-table study_title.qza 		--i-taxonomy taxonomy.qza 		--p-level 6 		--o-collapsed-table lvl6-study_title.qza
  qiime composition add-pseudocount 		--i-table lvl6-study_title.qza 		--o-composition-table comp-lvl6-study_title.qza
  qiime composition ancom 		--i-table comp-lvl6-study_title.qza 		--m-metadata-file Metadata_PRJEB11689.tsv 		--m-metadata-column study_title 		--o-visualization comp-lvl6-study_title.qzv
  qiime tools export --input-path comp-lvl6-study_title.qzv 		--output-path ancom/Category-study_title-level-6

Command exit status:
  1

Command output:
  Saved FeatureTable[Frequency] to: lvl6-study_title.qza
  Saved FeatureTable[Composition] to: comp-lvl6-study_title.qza

Command error:
  Plugin error from composition:
  
    All values the `grouping` are the same. This method cannot operate on a grouping vector with only a single group of samples(e.g., there are no 'between' variance because there is only a single group).
  
  Debug info has been saved to /tmp/qiime2-q2cli-err-izpkghl5.log

Work dir:
  /nfs/home/students/achauhan/work/c7/f04c0f1ccee6aa4ba945156347d0c2

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run
```

**Comment by AparnaChauhan** [comment]
> Probably you need to troubleshoot this with your admin/cluster support, this doesn't seem to be a problem with the pipeline

But the same command for other datafile seems to work fine the classifier, in that I'm getting a completely different error.

```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'ancom_tax (study_title-level6)'

n error from composition:

    All values the `grouping` are the same. This method cannot operate on a grouping vector with only a single group of
samples(e.g., there are no 'between' variance because there is only a single group).Caused by:
  Process `ancom_tax (study_title-level6)` terminated with an error exit status (1)

Command executed:

  qiime taxa collapse 		--i-table study_title.qza 		--i-taxonomy taxonomy.qza 		--p-level 6 		--o-collapsed-table lvl6-study_title.qza
  qiime composition add-pseudocount 		--i-table lvl6-study_title.qza 		--o-composition-table comp-lvl6-study_title.qza
  qiime composition ancom 		--i-table comp-lvl6-study_title.qza 		--m-metadata-file Metadata_PRJEB11689.tsv 		--m-metadata-column study_title 		--o-visualization comp-lvl6-study_title.qzv
  qiime tools export --input-path comp-lvl6-study_title.qzv 		--output-path ancom/Category-study_title-level-6

Command exit status:
  1

Command output:
  Saved FeatureTable[Frequency] to: lvl6-study_title.qza
  Saved FeatureTable[Composition] to: comp-lvl6-study_title.qza

Command error:
  Plugin error from composition:
  
    All values the `grouping` are the same. This method cannot operate on a grouping vector with only a single group of samples(e.g., there are no 'between' variance because there is only a single group).
  
  Debug info has been saved to /tmp/qiime2-q2cli-err-izpkghl5.log

Work dir:
  /nfs/home/students/achauhan/work/c7/f04c0f1ccee6aa4ba945156347d0c2

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run
```

**Comment by d4straub** [comment]
This is an unrelated problem. Your metadata is insufficient for this statistic. Obviously the metadata column specified has only one value (but must have several).

**Comment by AparnaChauhan** [comment]
Okay Thanks!

> OSError: [Errno 30] Read-only file system: '/nfs/home/users'

But I was confused about why am I not getting the same error for the classifier process when I'm running the other data-file?

**Comment by d4straub** [comment]
No idea. Did you resume the data-file that failed? Sometimes clusters have hickups and a retry works. 

To avoid error messages about your metadata you can either just not specify it or skip certain processes such as `--skip_ancom`

**Comment by AparnaChauhan** [comment]
I get the error -
```
Unable to acquire lock on session with ID 7a5cf176-38f9-4ebb-b07d-cb99282d1ba5

Common reasons of this error are:
 - You are trying to resume the execution of an already running pipeline
 - A previous execution was abruptly interrupted leaving the session open

You can check what process is holding the lock file by using the following command:
 - lsof /nfs/home/students/achauhan/.nextflow/cache/7a5cf176-38f9-4ebb-b07d-cb99282d1ba5/db/LOCK

```
while trying to resume the pipeline.
Will deleting the LOCK file help?

**Comment by d4straub** [comment]
Make sure that there is no pipeline running in the directory and it might help to remove the lock. Haven't done that yet myself yet, was never needed.

**Comment by AparnaChauhan** [comment]
Okay , Thank you!
> OSError: [Errno 30] Read-only file system: '/nfs/home/users'

For the above mentioned error changing the joblib directory in config file worked, thanks for pointing out the error. 
Closing this issue now!
