### ISSUE TITLE
Output format cannot be FASTQ since no quality values are available

### ISSUE THREAD

**Issue by johnne** [nf-core/ampliseq#527]
### Description of the bug

When running the pipeline with `cut_dada_ref_taxonomy = true` I get an error at the `NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_TAXONOMY (assignTaxonomy)` process. It seems cutadapt complains about writing to fastq-output when input is fasta. This is the error message from nextflow:

```bash
Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_TAXONOMY (assignTaxonomy)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_TAXONOMY (assignTaxonomy)` terminated with an error exit status (1)

Command executed:

  cutadapt \
      --cores 1 \
      --discard-untrimmed --minimum-length 1 -g GTGYCAGCMGCCGCGGTAA...ATTAGAWACCCBNGTAGTCC \
      -o assignTaxonomy.trim.fastq.gz \
      assignTaxonomy.fna \
      > assignTaxonomy.cutadapt.log
...
```

and at the end of the python error trace is:

```bash
  ValueError: Output format cannot be FASTQ since no quality values are available.
```

### Command used and terminal output

```console
nextflow run . -profile test,singularity --outdir ./results --max_cpus 1

Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_TAXONOMY (assignTaxonomy)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_TAXONOMY (assignTaxonomy)` terminated with an error exit status (1)

Command executed:

  cutadapt \
      --cores 1 \
      --discard-untrimmed --minimum-length 1 -g GTGYCAGCMGCCGCGGTAA...ATTAGAWACCCBNGTAGTCC \
      -o assignTaxonomy.trim.fastq.gz \
      assignTaxonomy.fna \
      > assignTaxonomy.cutadapt.log
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_TAXONOMY":
      cutadapt: $(cutadapt --version)
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: /etc/singularity/ exists, migration to apptainer by system administrator is not complete                                                           [63/1955]
  WARNING: DEPRECATED USAGE: Environment variable SINGULARITYENV_TMPDIR will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Environment variable SINGULARITYENV_NXF_DEBUG will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  Traceback (most recent call last):
    File "/usr/local/bin/cutadapt", line 10, in <module>
      sys.exit(main_cli())
    File "/usr/local/lib/python3.9/site-packages/cutadapt/__main__.py", line 848, in main_cli
      main(sys.argv[1:])
    File "/usr/local/lib/python3.9/site-packages/cutadapt/__main__.py", line 902, in main
      runner = setup_runner(pipeline, inpaths, outfiles, progress, cores, args.buffer_size, file_opener)
    File "/usr/local/lib/python3.9/site-packages/cutadapt/__main__.py", line 951, in setup_runner
      return SerialPipelineRunner(pipeline, infiles, outfiles, progress)
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 863, in __init__
      self._pipeline.connect_io(infiles, outfiles)
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 176, in connect_io
      self._set_output(outfiles)
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 256, in _set_output
      self._filters.append(self._final_filter(outfiles))
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 358, in _final_filter
      writer = self._open_writer(outfiles.out, force_fasta=outfiles.force_fasta)
    File "/usr/local/lib/python3.9/site-packages/cutadapt/pipeline.py", line 347, in _open_writer
      return self.file_opener.dnaio_open_raise_limit(
    File "/usr/local/lib/python3.9/site-packages/cutadapt/utils.py", line 218, in dnaio_open_raise_limit
      return open_raise_limit(self.dnaio_open, *args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/cutadapt/utils.py", line 51, in open_raise_limit
      f = func(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/cutadapt/utils.py", line 208, in dnaio_open
      f = dnaio.open(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/dnaio/__init__.py", line 117, in open
      return _open_single(
    File "/usr/local/lib/python3.9/site-packages/dnaio/__init__.py", line 209, in _open_single
      raise ValueError(
  ValueError: Output format cannot be FASTQ since no quality values are available.
```

### Relevant files

[nextflow.log](https://github.com/nf-core/ampliseq/files/10545008/nextflow.log)

### System information

nextflow version 22.10.2.5832
Hardware: HPC
OS: CentOS version 7
Container engine: Singularity
Version of nf-core/ampliseq: `master` (commit 83877d2) and `dev` (commit 5ceb03f) branches

**Comment by d4straub** [comment]
That is mysterious. Because `test.config` contains `cut_dada_ref_taxonomy = true` and it works in CI tests and local. 
But you run a local copy of the pipeline with `nextflow run . -profile test,singularity --outdir ./results --max_cpus 1` instead of proper release version, anything can go wrong that way... Please try out `nextflow run nf-core/ampliseq -r 2.4.1 -profile test,singularity --outdir ./results --max_cpus 1`

**Comment by johnne** [comment]
It also works when I run with `-profile uppmax,test` instead of `-profile test,singularity`

**Comment by johnne** [comment]
Yes, when running with `-profile uppmax,test` I see the CUTADAPT_TAXONOMY process finish at `[100%]`

**Comment by d4straub** [comment]
Alright, thanks for the update, than this problem is resolved, glad to hear!
