### ISSUE TITLE
CUTADAPT Workflow error 

### ISSUE THREAD

**Issue by aqsakhalid03** [nf-core/ampliseq#649]
### Description of the bug

I am getting error when i try to pull ampliseq pipeline and the error is at CUTADAPT step. How can i resolve this issue. 
![Screenshot from 2023-10-18 07-38-39](https://github.com/nf-core/ampliseq/assets/144911567/24ae8c42-05b8-4f44-a925-5a4d68215d72)

### Command used and terminal output

```console
command to pull pipeline: nextflow run nf-core/ampliseq -r 2.6.1 -profile test --outdir test_output_ampliseq -resume

Error: 
[nf-core/ampliseq] Pipeline completed with errors-
WARN: Killing running tasks (2)
WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
ERROR ~ Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC (sampleID_1)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC (sampleID_1)` terminated with an error exit status (127)

Command executed:

  cutadapt \
      --cores 2 \
      --minimum-length 1 -O 3 -e 0.1 -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT --discard-untrimmed \
      -o sampleID_1.trimmed_1.trim.fastq.gz -p sampleID_1.trimmed_2.trim.fastq.gz \
      sampleID_1_1.fastq.gz sampleID_1_2.fastq.gz \
      > sampleID_1.trimmed.cutadapt.log
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:CUTADAPT_WORKFLOW:CUTADAPT_BASIC":
      cutadapt: $(cutadapt --version)
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 3: cutadapt: command not found

Work dir:
  /home/aqsakhalid/work/da/7dab70da51dbd3d5aeac7ab4e046b9

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
ERROR ~ Cannot invoke method getAt() on null object

 -- Check script '.nextflow/assets/nf-core/ampliseq/./workflows/../subworkflows/local/dada2_preprocessing.nf' at line: 59 or see '.nextflow.log' file for more details
```

**Comment by d4straub** [comment]
Hi there,

did you indeed use the command `nextflow run nf-core/ampliseq -r 2.6.1 -profile test --outdir test_output_ampliseq -resume` to start the pipeline? Because missing is the software management tool, e.g. docker, singularity, or such, see https://nf-co.re/docs/usage/introduction#how-to-run-a-pipeline or https://nf-co.re/ampliseq/2.6.1#usage.

Essentially, after having installed e.g. singularity, use:
`nextflow run nf-core/ampliseq -r 2.6.1 -profile test,singularity --outdir test_output_ampliseq -resume`

**Comment by aqsakhalid03** [comment]
Yes, i was able to resolve it by assigning profile. 
Command: 
After running the above command i encounter below error: 
nextflow run nf-core/ampliseq -r 2.6.1 -profile test,docker --outdir test_output_ampliseq -resume
-[nf-core/ampliseq] Pipeline completed with errors-
WARN: Killing running tasks (2)
ERROR ~ Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_DIVERSITY:QIIME2_DIVERSITY_CORE (1)'

Caused by:
  Process `NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_DIVERSITY:QIIME2_DIVERSITY_CORE (1)` terminated with an error exit status (1)

Command executed:

  export XDG_CONFIG_HOME="${PWD}/HOME"
  
  mindepth=$(count_table_minmax_reads.py filtered-table.tsv minimum 2>&1)
  if [ "$mindepth" -lt "500" ]; then mindepth=500; fi
  
  # report the rarefaction depth and return warning, if needed
  if [ "$mindepth" -lt "1000" ]; then
      echo $mindepth >"WARNING The sampling depth of $mindepth seems too small for rarefaction.txt"
  elif [ "$mindepth" -lt "5000" ]; then
      echo $mindepth >"WARNING The sampling depth of $mindepth is very small for rarefaction.txt"
  elif [ "$mindepth" -lt "10000" ]; then
      echo $mindepth >"WARNING The sampling depth of $mindepth is quite small for rarefaction.txt"
  else
      echo $mindepth >"Use the sampling depth of $mindepth for rarefaction.txt"
  fi
  
  qiime diversity core-metrics-phylogenetic \
      --m-metadata-file Metadata.tsv \
      --i-phylogeny rooted-tree.qza \
      --i-table filtered-table.qza \
      --p-sampling-depth $mindepth \
      --output-dir diversity_core \
      --p-n-jobs-or-threads 2 \
      --verbose
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_DIVERSITY:QIIME2_DIVERSITY_CORE":
      qiime2: $( qiime --version | sed '1!d;s/.* //' )
  END_VERSIONS

Command exit status:
  1

Command output:
  Running external command line application. This may print messages to stdout and/or stderr.
  The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.
  
  Command:
  
  faithpd -i /tmp/qiime2/aqsakhalid/data/da179667-983f-4757-9b74-44b0843b86eb/data/feature-table.biom -t /tmp/qiime2/aqsakhalid/data/a0ff32a4-a120-4e2a-8f79-6cc096caa443/data/tree.nwk -o /tmp/q2-AlphaDiversityFormat-0fcyomms
  
  Running external command line application. This may print messages to stdout and/or stderr.
  The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.
  
  Command:
  
  ssu -i /tmp/qiime2/aqsakhalid/data/da179667-983f-4757-9b74-44b0843b86eb/data/feature-table.biom -t /tmp/qiime2/aqsakhalid/data/a0ff32a4-a120-4e2a-8f79-6cc096caa443/data/tree.nwk -m unweighted -o /tmp/q2-LSMatFormat-kzwg_8k_

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/q2cli/commands.py", line 352, in __call__
      results = action(**arguments)
    File "<decorator-gen-227>", line 2, in core_metrics_phylogenetic
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/qiime2/sdk/action.py", line 234, in bound_callable
      outputs = self._callable_executor_(scope, callable_args,
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/qiime2/sdk/action.py", line 475, in _callable_executor_
      outputs = self._callable(scope.ctx, **view_args)
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/q2_diversity/_core_metrics.py", line 66, in core_metrics_phylogenetic
      dms += unweighted_unifrac(table=cr.rarefied_table, phylogeny=phylogeny,
    File "<decorator-gen-477>", line 2, in unweighted_unifrac
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/qiime2/sdk/action.py", line 234, in bound_callable
      outputs = self._callable_executor_(scope, callable_args,
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/qiime2/sdk/action.py", line 381, in _callable_executor_
      output_views = self._callable(**view_args)
    File "<decorator-gen-147>", line 2, in unweighted_unifrac
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/q2_diversity_lib/_util.py", line 69, in _disallow_empty_tables
      return wrapped_function(*args, **kwargs)
    File "<decorator-gen-146>", line 2, in unweighted_unifrac
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/q2_diversity_lib/_util.py", line 112, in _validate_requested_cpus
      return wrapped_function(*bound_arguments.args, **bound_arguments.kwargs)
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/q2_diversity_lib/beta.py", line 221, in unweighted_unifrac
      _omp_cmd_wrapper(threads, cmd)
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/q2_diversity_lib/_util.py", line 128, in _omp_cmd_wrapper
      return _run_external_cmd(cmd, verbose=verbose, env=env)
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/site-packages/q2_diversity_lib/_util.py", line 122, in _run_external_cmd
      return subprocess.run(cmd, check=True, env=env)
    File "/opt/conda/envs/qiime2-2022.11/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['ssu', '-i', '/tmp/qiime2/aqsakhalid/data/da179667-983f-4757-9b74-44b0843b86eb/data/feature-table.biom', '-t', '/tmp/qiime2/aqsakhalid/data/a0ff32a4-a120-4e2a-8f79-6cc096caa443/data/tree.nwk', '-m', 'unweighted', '-o', '/tmp/q2-LSMatFormat-kzwg_8k_']' returned non-zero exit status 1.
  
  Plugin error from diversity:
  
    Command '['ssu', '-i', '/tmp/qiime2/aqsakhalid/data/da179667-983f-4757-9b74-44b0843b86eb/data/feature-table.biom', '-t', '/tmp/qiime2/aqsakhalid/data/a0ff32a4-a120-4e2a-8f79-6cc096caa443/data/tree.nwk', '-m', 'unweighted', '-o', '/tmp/q2-LSMatFormat-kzwg_8k_']' returned non-zero exit status 1.
  
  See above for debug info.
  Running external command line application. This may print messages to stdout and/or stderr.
  The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.
  
  Command:
  
  faithpd -i /tmp/qiime2/aqsakhalid/data/da179667-983f-4757-9b74-44b0843b86eb/data/feature-table.biom -t /tmp/qiime2/aqsakhalid/data/a0ff32a4-a120-4e2a-8f79-6cc096caa443/data/tree.nwk -o /tmp/q2-AlphaDiversityFormat-0fcyomms
  
  Running external command line application. This may print messages to stdout and/or stderr.
  The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.
  
  Command:
  
  ssu -i /tmp/qiime2/aqsakhalid/data/da179667-983f-4757-9b74-44b0843b86eb/data/feature-table.biom -t /tmp/qiime2/aqsakhalid/data/a0ff32a4-a120-4e2a-8f79-6cc096caa443/data/tree.nwk -m unweighted -o /tmp/q2-LSMatFormat-kzwg_8k_

Work dir:
  /home/aqsakhalid/work/9d/a566de81b4c98751b3971ec14539e1

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by d4straub** [comment]
The test profile in ampliseq works. This command you are using is there to confirm that the computational setup you are using is fine. And, concluding from that error, its not. However, from that error message, I cannot identify the problem with certainty.

Do you have a GPU in the framework of your compute infrastructure? 
If yes, waiting for the next release might help, see https://github.com/nf-core/ampliseq/pull/633, just around the corner, this or next week is the release planned.  
If no, could you (1) resume and check whether that problem is persistent (or just temporal) and (2) add https://nf-co.re/ampliseq/2.6.1/parameters#skip_diversity_indices to your command to check whether all other processes pass (i.e. only QIIME2_DIVERSITY_CORE is the problem).

**Comment by aqsakhalid03** [comment]
Yes, I have a GPU in the framework of your compute infrastructure. I tried --skip_diversity_indices and the pipeline completed successfully. Would we be able to include diversity indices after the next release? 
Thank you
