### ISSUE TITLE
Make classifier exceeds time limit

### ISSUE THREAD

**Issue by alneberg** [nf-core/ampliseq#77]
Hello!
I get the following error:
```
ERROR ~ Error executing process > 'make_SILVA_132_16S_classifier (1)'

Caused by:
  Process exceeded running time limit (3h)
```
Which shuts down the nextflow execution (version  18.10.1 build 5003). I guess my data set is too large (258 samples, 1 MiSeq lane ~4.8GB zipped fastqs)?

The process is not restarted either even though the `.exitcode` file gives `143` which should be retried?

**Comment by d4straub** [comment]
Hi,
the process `make_SILVA_132_16S_classifier` shouldn't run into trouble usually since it is independent from your read data. It only depends on the SILVA database (which is downloaded) and the primer sequences you supplied. Do you have more information such as the `.nextflow.log` or `.command.log` in the process directory? Maybe there is more to work with.

**Comment by alneberg** [comment]
Ok, here goes. The nextflow log was not really helpful (I think):
```
Mar-07 14:16:40.416 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: make_SILVA_132_16S_classifier (1); status: COMPLETED; exit: -; error: nextflow.exception.ProcessException: Process exceeded running time limit (3h); workDir: /PATH/work/c6/9bb8c5c1bcdb7c160e690ccccd1889]
Mar-07 14:16:40.453 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'make_SILVA_132_16S_classifier (1)'

Caused by:
  Process exceeded running time limit (3h)

Command executed:

  unzip -qq Silva_132_release.zip

          fasta="SILVA_132_QIIME_release/rep_set/rep_set_16S_only/99/silva_132_99_16S.fna"
          taxonomy="SILVA_132_QIIME_release/taxonomy/16S_only/99/consensus_taxonomy_7_levels.txt"

          if [ "false" = "true" ]; then
                    sed 's/#//g' $taxonomy >taxonomy-99_removeHash.txt
                    taxonomy="taxonomy-99_removeHash.txt"
                    echo "
  ######## WARNING! The taxonomy file was altered by removing all hash signs!"
          fi

            ### Import
            qiime tools import --type 'FeatureData[Sequence]'           --input-path $fasta             --output-path ref-seq-99.qza
            qiime tools import --type 'FeatureData[Taxonomy]'           --source-format HeaderlessTSVTaxonomyFormat             --input-path $taxonomy          --output-path ref-taxonomy-99.qza

            #Extract sequences based on primers
            qiime feature-classifier extract-reads              --i-sequences ref-seq-99.qza            --p-f-primer CCTACGGGNGGCWGCAG          --p-r-primer GACTACHVGGGTATCTAATCC              --o-reads CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-ref-seq.qza         --quiet

            #Train classifier
            qiime feature-classifier fit-classifier-naive-bayes                 --i-reference-reads CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-ref-seq.qza              --i-reference-taxonomy ref-taxonomy-99.qza              --o-classifier CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-classifier.qza         --quiet

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /PATH/work/c6/9bb8c5c1bcdb7c160e690ccccd1889

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

The contents of the work directory shows empty .command.log and .command.err:
```
drwxrwsr-x  5 alneberg sllstore2017079     4096 Mar  7 14:16 .
drwxrwsr-x 12 alneberg sllstore2017079     4096 Mar  7 11:15 ..
-rw-r--r--  1 alneberg sllstore2017079 26115352 Mar  7 11:41 CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-ref-seq.qza
-rw-rw-r--  1 alneberg sllstore2017079        0 Mar  7 11:16 .command.begin
-rw-rw-r--  1 alneberg sllstore2017079        0 Mar  7 11:16 .command.err
-rw-rw-r--  1 alneberg sllstore2017079        0 Mar  7 11:16 .command.log
-rw-rw-r--  1 alneberg sllstore2017079        0 Mar  7 11:16 .command.out
-rw-rw-r--  1 alneberg sllstore2017079     2856 Mar  7 11:16 .command.run
-rw-rw-r--  1 alneberg sllstore2017079     1336 Mar  7 11:16 .command.sh
-rw-rw-r--  1 alneberg sllstore2017079     3553 Mar  7 11:16 .command.stub
-rw-r--r--  1 alneberg sllstore2017079      200 Mar  7 14:16 .command.trace
-rw-rw-r--  1 alneberg sllstore2017079        3 Mar  7 14:16 .exitcode
drwxrwsr-x  3 alneberg sllstore2017079     4096 Apr 10  2018 __MACOSX
-rw-r--r--  1 alneberg sllstore2017079 94255418 Mar  7 11:19 ref-seq-99.qza
-rw-r--r--  1 alneberg sllstore2017079  8733550 Mar  7 11:19 ref-taxonomy-99.qza
drwx--S---  8 alneberg sllstore2017079     4096 Apr 10  2018 SILVA_132_QIIME_release
lrwxrwxrwx  1 alneberg sllstore2017079      183 Mar  7 11:16 Silva_132_release.zip -> /PATH/work/c6/9bb8c5c1bcdb7c160e690ccccd1889/tmp/fb/260359568b8da6c933265a5a7c932e/Silva_132_release.zip
drwxrwsr-x  3 alneberg sllstore2017079     4096 Mar  7 11:15 tmp
```

The .command.trace gives:
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
2 0 1279 234 32351608 30731044 32351620 30856964 5582174145 7798393709 517759 191223 63654912 7799156736
```

Anything else that could be useful? I could run it again and see which commands that seems to take the most time, but that requires some manual work.

**Comment by d4straub** [comment]
Thanks.

You are right, not very useful information in the logs.
However, the contents of the work directory show that everything worked until the last command. The remaining 2h 30 min were not sufficient to finish, that's quite weird. According to my experience slightly above 2h are sufficient for the whole process.

The last command that wasnt finished is
```
#Train classifier
qiime feature-classifier fit-classifier-naive-bayes \
	--i-reference-reads CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-ref-seq.qza \
	--i-reference-taxonomy ref-taxonomy-99.qza \
	--o-classifier CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-classifier.qza
```
Maybe you could use the singularity image in `work/singularity/` to execute the above command in the work directory to see if it works. Following this you could copy the trained classifier somewhere and subsequently use it with `--classifier path/to/classifier.qza` in the pipeline.

**Comment by alneberg** [comment]
Thanks! Yes, I'll try this right away!

I agree it would be good to increase the time limit. Doesn't hurt much if it's too high.

**Comment by alneberg** [comment]
I got this error when running in the singularity image:
```
singularity shell /PATH/ampliseq/singularity_cache/nfcore-ampliseq-1.0.0.img
qiime feature-classifier fit-classifier-naive-bayes --i-reference-reads CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-ref-seq.qza --i-reference-taxonomy ref-taxonomy-99.qza --o-classifier CCTACGGGNGGCWGCAG-GACTACHVGGGTATCTAATCC-99-classifier.qza
Traceback (most recent call last):
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2cli/commands.py", line 244, in __call__
    arguments, missing_in, verbose, quiet = self.handle_in_params(kwargs)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2cli/commands.py", line 326, in handle_in_params
    kwargs, fallback=cmd_fallback)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2cli/handlers.py", line 375, in get_value
    artifact = qiime2.sdk.Result.load(path)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/sdk/result.py", line 65, in load
    archiver = archive.Archiver.load(filepath)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/core/archive/archiver.py", line 301, in load
    return cls(path, Format(rec))
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/core/archive/format/v1.py", line 29, in __init__
    super().__init__(archive_record)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/core/archive/format/v0.py", line 72, in __init__
    self.type = sdk.parse_type(type)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/sdk/util.py", line 57, in parse_type
    pm = qiime2.sdk.PluginManager()
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2_vsearch/plugin_setup.py", line 12, in <module>
    import q2_vsearch._cluster_features
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/q2_vsearch/_cluster_features.py", line 15, in <module>
    import skbio
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/skbio/__init__.py", line 13, in <module>
    import skbio.io  # noqa
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/skbio/io/__init__.py", line 238, in <module>
    import_module('skbio.io.format.lsmat')
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/skbio/io/format/lsmat.py", line 77, in <module>
    from skbio.stats.distance import DissimilarityMatrix, DistanceMatrix
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/skbio/stats/distance/__init__.py", line 192, in <module>
    from ._base import (DissimilarityMatrixError, DistanceMatrixError,
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/skbio/stats/distance/_base.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/opt/conda/envs/nf-core-ampliseq-1.0.0/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Btw, I'm running the release version 1.0.0. Is this a bug in the singularity container? Or did I just run it in the wrong way?

**Comment by d4straub** [comment]
The container should be fine, I think we came across that problem of a missing library before and solved it. 
@apeltzer any idea here? Could this be the problem with the matplotlib?

**Comment by alneberg** [comment]
I ran `echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc` in the singularity container and not it seems to run...

Strange, this should be already set in the singularity image right?

**Comment by alneberg** [comment]
Could be some strange mixup of paths between the local file system and the mounted one inside the container when running it interactively. So this particular ImportError is probably a bug which is on my local execution and not when running it with nextflow. So you can ignore this particular error for now.

**Comment by d4straub** [comment]
We had problems with matplotlib and Alex solved that problem for the pipeline but I don't remember the details. 

Glad it runs for now.

**Comment by d4straub** [comment]
Time for classifier training is increased and increased maxRetries to 3.
